### PR TITLE
Only show alert for the map once

### LINKED ISSUE #153: Use cookies to only call out to map once
:cookie:

### PR DESCRIPTION
**Pull request by evantarrh**
review: @natebrennand @RaymondXu @jzf2101

after the first visit to the site, a cookie is set so that the map alert is not shown on capacity.html

closes #153!

### CODE REVIEW

**Comment by natebrennand** [comment]
This looks like it will work fine.
However, I don't totally see how it's necessary and I also think it should just be in JS if it is.

**Comment by evantarrh** [comment]
hmm okay! how would you do this in JS without cookies? or would it be better to not do this at all and always promote the map feature?

**Comment by natebrennand** [comment]
You'd still use cookies, this just seems like something that shouldn't be server-side to me.
I generally think that the API and the website should be in separate repositories.

**Comment by evantarrh** [comment]
actually i think you are right after discussing with the team––people would be more likely to just miss it and not pay attention.

closing this PR!

**Pull request closed without merging**
