### PR TITLE
Make progress bar empty for <= 2%. (Fixes relative widths bug)

### PR DESCRIPTION
**Pull request by RaymondXu**

### CODE REVIEW

**Comment by natebrennand** [comment]
can you include screenshots of how it now appears?

**Comment by RaymondXu** [comment]
Desktop:
screen shot 2015-02-27 at 3 33 03 pm

Mobile:
screen shot 2015-02-27 at 3 40 42 pm

**Comment by evantarrh** [comment]
:+1:

**Comment by jzf2101** [comment]
:+1: yay!

On Feb 27, 2015, at 18:27, Evan Tarrh <notifications@github.com> wrote:

[image: :+1:]

—
Reply to this email directly or view it on GitHub
<https://github.com/adicu/density/pull/116#issuecomment-76492030>.

**Pull request merged**
