### PR TITLE
accessing the database from postgresql also last updated info

### PR DESCRIPTION
**Pull request by jzf2101**
now added to the readme

### CODE REVIEW

**Comment by natebrennand** [comment]
should we add a note that you need to be in the vagrant box to call this?

also, a link to an intro to SQL might be nice.

**Comment by jzf2101** [comment]
@natebrennand good point will add that

**Comment by natebrennand** [comment]
@jzf2101, it looks like you forgot to switch off this branch before making changes

**Comment by jzf2101** [comment]
screen shot 2015-04-17 at 16 14 16

**Comment by jzf2101** [comment]
Closes #63

**Comment by swbae31** [comment]
:+1:

**Comment by natebrennand** [comment]
:+1:

**Comment by jzf2101** [comment]
screen shot 2015-04-17 at 16 57 07

**Comment by jzf2101** [comment]
screen shot 2015-04-17 at 17 10 51

**Pull request merged**
