### PR TITLE
Add a mapping route, fix a documentation issue, and add a documentation example

### PR DESCRIPTION
**Pull request by maclyn**

### CODE REVIEW

**Comment by maclyn** [comment]
I added basic mapping functionality using the method Nate suggested with a new route (/map). Some JavaScript on the a new HTML page will highlight an SVG of Columbia taken from the college's walking tour PDF. Before releasing this, someone would need to contact an administrator to make sure we can use the map image; otherwise we could replace it with an SVG taken from (http://www.openstreetmap.org/way/169626373#map=18/40.80861/-73.96089), which seems like it has a permissive enough license to use. The only changes that'd be needed after exporting it would be changing the ID of certain building paths to "parent_[parent ID]". There's support for showing % that building are full on mouseover (although the positioning JS needs some work), and it opens a Google search for hours when you click on the buildings. The opacity of buildings is set by % full. 
screenshot

**Comment by natebrennand** [comment]
that looks really great!
should we change the buildings that we do not have info for to some other color?

regarding the image, it's better to ask for forgiveness.

**Comment by maclyn** [comment]
Yeah, I was thinking about that -- the colors and stuff were temporary placeholders. Ideally, it would set some sort of linear gradient in the SVG for the buildings we were using and change the position of a couple stops to make buildings appear a certain percent full, and I think that would distinguish them enough, but I had a lot of trouble setting it via JavaScript. If someone knows how to do that, I think that'd be ideal.

**Comment by jzf2101** [comment]
Yay! :100:

**Comment by maclyn** [comment]
Yo can we merge (or selectively merge, if such a thing is possible) the documentation stuff at least? People are going to get confused if we don't have some of that.

**Comment by natebrennand** [comment]
i separated the docs commit and made another PR. plz check then we can merge

**Comment by maclyn** [comment]
Created a new pull request for the other branch.

**Pull request closed without merging**
