### PR TITLE
Mudd noco map swap

### PR DESCRIPTION
**Pull request by evantarrh**
* Fixing `map.svg` so that Mudd is now NoCo
* Updating `capacity_group.json` to reflect changes in data. @natebrennand @jzf2101 can you confirm that this is the correct way to make this change?

### CODE REVIEW

**Comment by jzf2101** [comment]
:+1:  yay

**Comment by jzf2101** [comment]
@evantarrh FYI the data should be changing the language to Northwest Corner Building 

See: https://github.com/adicu/wireless_data_processor/issues/4

**Comment by evantarrh** [comment]
@jzf2101 That's what I was asking about––are the changes I'm making to `capacity_group.json` the right way to do that?

**Comment by jzf2101** [comment]
@evantarrh this has 2 parts, capacity_group is definitely one part.  The other part requires fixing the actual dataset.  @natebrennand is working on that.

**Comment by jzf2101** [comment]
@evantarrh since @natebrennand pr'd all we need to do is to change `capacity_group`

**Comment by natebrennand** [comment]
Make sure to reprovision your Vagrant so that the database data is updated!

**Comment by jzf2101** [comment]
We'd need to update the test dataset correct @natebrennand ?

**Comment by natebrennand** [comment]
see https://github.com/adicu/density/pull/170

**Comment by evantarrh** [comment]
This is all set, then! Are we :+1: to merge?

**Comment by natebrennand** [comment]
screenshot?

**Comment by evantarrh** [comment]
screenshot 2015-05-01 15 09 53
(The fact that it's showing as 100% is because of the test database; it will work properly with real data)

**Comment by natebrennand** [comment]
:+1:

**Pull request merged**
