### PR TITLE
Softening Language in API Login Email Error

### LINKED ISSUE #121: Wrong Email error seems slightly aggressive
screen shot 2015-03-01 at 11 14 34 pm

### PR DESCRIPTION
**Pull request by jzf2101**
screen shot 2015-04-04 at 15 10 17
 Closes #121

### CODE REVIEW

**Comment by jzf2101** [comment]
When I reran travis's `flake8 density` I get the following errors:

```
4dmac:density 4d$ flake8 density/
density/config/flask_config.py:62:1: E402 module level import not at top of file
density/density.py:10:1: E402 module level import not at top of file
density/density.py:15:1: E402 module level import not at top of file
density/density.py:16:1: E402 module level import not at top of file
density/density.py:17:1: E402 module level import not at top of file
density/density.py:18:1: E402 module level import not at top of file
density/density.py:19:1: E402 module level import not at top of file
density/density.py:20:1: E402 module level import not at top of file
density/density.py:21:1: E402 module level import not at top of file
density/density.py:22:1: E402 module level import not at top of file
density/density.py:23:1: E402 module level import not at top of file
density/density.py:24:1: E402 module level import not at top of file
density/density.py:25:1: E402 module level import not at top of file
density/density.py:204:35: W503 line break before binary operator
density/density.py:215:36: W503 line break before binary operator
density/density.py:215:80: E501 line too long (82 > 79 characters)
density/density.py:216:36: W503 line break before binary operator
density/density.py:217:36: W503 line break before binary operator
```

Should I rework all these errors?

**Comment by evantarrh** [comment]
we might still want to make the text smaller or less red? still pretty abrasive/unfriendly.

**Comment by jzf2101** [comment]
@evantarrh fair we should fix the styling

**Comment by jzf2101** [comment]
@evantarrh How about this?

screen shot 2015-04-11 at 17 39 12

**Comment by jzf2101** [comment]
Also, as a stylistic issue here I made all the instances of the word email in docs and the auth page spell email without a dash

**Comment by evantarrh** [comment]
Lgtm

**Comment by RaymondXu** [comment]
:+1:

**Pull request merged**
