### PR TITLE
Footer style

### LINKED ISSUE #139: footer should stick to bottom on big browsers & when pages have little content
screenshot 2015-03-27 17 10 52

### PR DESCRIPTION
**Pull request by evantarrh**
closes #139.

screenshot 2015-03-27 17 34 53

### CODE REVIEW

**Comment by natebrennand** [comment]
:+1: if you confirm you tested on all screen sizes (looks like you put the CSS in to support it thought so I assume you did)

**Comment by evantarrh** [comment]
Yup, works on all screen sizes!
screenshot 2015-03-27 18 14 08

**Comment by natebrennand** [comment]
:+1:

**Comment by jzf2101** [comment]
:+1:  Yay!

**Pull request merged**
