### PR TITLE
Add Navbar. Refactor logo and about info. Fix map bug. Minor padding adjustments.

### LINKED ISSUE #143: Refactor logo into layout.html instead of repeating it for each page

### PR DESCRIPTION
**Pull request by RaymondXu**
Review: @evantarrh @danrschlosser @natebrennand 

Closes #143, #146,  #150, #152,  #160 

Nav bar (screenshots updated to show new ordering):
screen shot 2015-04-17 at 4 37 49 pm

About page is currently a little bland, but the page is there now. We can add more info later.
screen shot 2015-04-17 at 4 37 55 pm

Mobile views:
img_0376
img_0379
img_0378
img_0377

Map bug is fixed by waiting until the SVG is loaded before calling the JS.
```
  function checkReady() {
    if (document.getElementById('map').getSVGDocument() == null) {
      setTimeout(checkReady, 5);
    }
    else {
      run();
    }
  }
```

### CODE REVIEW

**Comment by natebrennand** [comment]
can you include mobile screenshots as well / ack that you checked them?

**Comment by RaymondXu** [comment]
On it

**Comment by RaymondXu** [comment]
Also will change the order to 'HOME - MAP - ABOUT - API' as per @danrschlosser's opinion

**Comment by jzf2101** [comment]
:+1:

**Comment by swbae31** [comment]
:+1:

**Pull request merged**
