### PR TITLE
rerouting on 404, added 404 template

### PR DESCRIPTION
**Pull request by evantarrh**
screenshot 2015-03-27 14 43 52

Closes issue #130.

### CODE REVIEW

**Comment by natebrennand** [comment]
I like this a lot.
We should add a link to the documentation page, since they're usually going to hit a 404 when they're using a malformed URL

**Comment by natebrennand** [comment]
also, should it be "page", not "file"?

**Comment by evantarrh** [comment]
Cool, thanks––I made those changes and resolved conflicts with other PRs. The build still isn't passing, though––why is that?

**Comment by natebrennand** [comment]
here's the CI output:
```
$ flake8 density/
density/density.py:92:1: E302 expected 2 blank lines, found 1
The command "flake8 density/" exited with 1.
```

------

By the PEP8 standard, there must be 2 blanks lines between function declarations.
You can install `flake8` with pip and test files locally before pushing.
(or run the super convenient [tests.sh](https://github.com/adicu/density/blob/master/tests.sh) script)

**Comment by natebrennand** [comment]
It's possible to integrate flake8 or another pep8 syntax checker into your editor usually.

**Comment by jzf2101** [comment]
Looks cool! :+1:  after Travis says it's ready to go

**Comment by evantarrh** [comment]
Thanks Nate! everything should be :ok_hand: now

**Comment by natebrennand** [comment]
:100:

**Pull request merged**
